# Generated by Django 4.2.8 on 2023-12-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('freq', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='периодичность')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('is_positive', models.BooleanField(blank=True, default=False, null=True, verbose_name='положительность привычки')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='публичность')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='время на выполнение')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
